### PR TITLE
Endpoint API changes quick fix

### LINKED ISSUE #15: FYI: Dexcom seems to have changed their API response yesterday
I am calling the "ous" endpoint and yesterday my code started failing.

A response now looks like this for me. Not sure if this is a change top all endpoints or something specific to the OUS one.
`````
{"WT":"Date(1638296642000)","ST":"Date(1638296642000)","DT":"Date(1638296642000+0100)","Value":164,"Trend":"Flat"}
`````

I have identified 2 changes to the API response. And one maybe.

1. The dates do not have backslashes around them anymore.
2. Trend is no longer a number but instead it is a word.
3. I am not sure if DT always had a timezone offset? I am in Europe and that offset is right.

### PR DESCRIPTION
**Pull request by gagebenne**
Fixes #15

### CODE REVIEW

**Comment by gagebenne** [comment]
It seems there might be authentication-related changes to the endpoints as well. For now I'll ignore the trend arrow until more is known about the API changes.

**Comment by gagebenne** [comment]
This will have to do for now. This revealed the need for more resilient parsing -- perhaps in the next update.

**Comment by crosesvg** [comment]
Hi, 

I am running Home Assistant on the Home Assistant OS/VM on Windows. It seems that with this installation method I am unable to manually update to version 0.2.1 via pip3.

Any advice on how I can update my install to this version?

We use the Dexcom integration for alerting of us to our daughters hypos overnight (at least since the recent Dexcom update broke Sugarmate's integration)

Thanks

**Comment by gagebenne** [comment]
You should be able to see this update in the next release of Home Assistant (2021.12) this Saturday, December 11! If you so chose, the [beta](https://rc.home-assistant.io/blog/2021/12/03/release-202112/) is currently live, which has the updated `pydexcom`.

**Comment by crosesvg** [comment]
Thank you. 

I ended up joining the beta channel as I needed the fix ASAP.

**Pull request merged**
